services:
  backend:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./:/back-end
      - /back-end/node_modules
    depends_on:
      - mongo
    environment:
     - MONGO_URI=mongodb://mongo:27017/todoDB
     - PORT=5000  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db:/usr/local/var/mongodb
volumes:
  db:
    driver: local