services:
  backend:
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoDB
      - PORT=5000
  mongo:
    image: mongo
    volumes:
      - db:/usr/local/var/mongodb

volumes:
  db:
    driver: local
